#!/usr/bin/env node
/**
 * Generates THIRD-PARTY-NOTICES.md from the `source` blocks on assets.
 *
 * Derived rather than hand-written on purpose. A notices file maintained by
 * hand goes stale the first time someone imports a set and forgets — and a
 * stale attribution file is a license problem, not a documentation one. This
 * reads what is actually in assets/, so it cannot disagree with reality.
 *
 * Run: npm run notices  (and it is part of `npm run build`)
 */
import { readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { collectAssets } from './build-manifest.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

async function main() {
  const assets = await collectAssets();
  const vendored = assets.filter((a) => a.source);

  /* Group by project, keeping the license and copyright, and noting which
     collections it turns up in — that is what an auditor actually needs. */
  const byProject = new Map();
  for (const asset of vendored) {
    const key = asset.source.project;
    const entry = byProject.get(key) || {
      ...asset.source,
      count: 0,
      collections: new Set(),
      synthesised: 0,
    };
    entry.count++;
    entry.collections.add(`${asset.type}s/${asset.collection}`);
    if (asset.notes?.includes('generated here')) entry.synthesised++;
    byProject.set(key, entry);
  }

  if (!byProject.size) {
    await writeFile(
      join(ROOT, 'THIRD-PARTY-NOTICES.md'),
      '# Third-party notices\n\nNo vendored third-party artwork in this repository.\n',
      'utf8'
    );
    console.log('Wrote THIRD-PARTY-NOTICES.md — nothing vendored.');
    return;
  }

  const lines = [
    '# Third-party notices',
    '',
    'Generated by `scripts/build-notices.mjs` from the `source` field on each',
    "asset, so it cannot drift from what the repository actually contains.",
    '',
  ];

  for (const [project, e] of [...byProject].sort((a, b) => b[1].count - a[1].count)) {
    lines.push(`## ${project}`);
    lines.push('');
    lines.push(`**${e.count.toLocaleString()} assets** in ${[...e.collections].map((c) => `\`assets/${c}/\``).join(', ')}`);
    lines.push('');
    if (e.copyright) lines.push(`${e.copyright}`);
    lines.push(`Used under **${e.license}**.`);
    if (e.url) lines.push(`Upstream: ${e.url.replace(/\/(tree|blob)\/.*$/, '')}`);
    lines.push('');
    if (e.synthesised) {
      lines.push(
        `> **${e.synthesised.toLocaleString()} of these carry a Standard variant that is not ${project} artwork.**`,
        '> It is generated by this repository, which insets the upstream glyph in a gradient',
        '> tile. Each affected asset says so in its `notes`. Do not present it as upstream design.',
        ''
      );
    }
  }

  lines.push('---');
  lines.push('');
  lines.push('Each asset carries its own `source` block naming the project, license,');
  lines.push('copyright and a link to the original file. The browser shows it in the detail');
  lines.push('panel, so the attribution is in front of whoever is about to copy the artwork.');
  lines.push('');

  await writeFile(join(ROOT, 'THIRD-PARTY-NOTICES.md'), lines.join('\n'), 'utf8');
  console.log(
    `Wrote THIRD-PARTY-NOTICES.md — ${byProject.size} project${byProject.size === 1 ? '' : 's'}, ${vendored.length} assets.`
  );
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
